name: AI PR Review (Groq)

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  review:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run AI Review
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LLM_PROVIDER: groq
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
        run: |
          # Download the PR reviewer script
          curl -o pr_reviewer.py https://raw.githubusercontent.com/YOUR-REPO/scripts/pr_reviewer.py
          curl -o llm_client.py https://raw.githubusercontent.com/YOUR-REPO/scripts/llm_client.py
          python pr_reviewer.py
